name: Build and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    container:
      image: swift:5.6-focal
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y make
    - name: Build
      run: |
        swift --version
        swift package --version
        swift build -v
    - name: Setup
      run: make setup
    - name: Generate the website
      run: make generate
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: sookim-1/sookim-1.github.io
        publish_branch: main
        publish_dir: ./Output
